services:
  server:
    build:
      context: ./server
    container_name: express-server
    ports:
      - "3000:3000"
    volumes:
      - attachments:/attachments
      - storage:/storage

  client:
    build:
      context: ./client
    container_name: vite-client
    ports:
      - "5173:3000"
    depends_on:
      - server

volumes:
  attachments:
  storage:
